# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b264c935cc4fbb836e611a21d613688c3f83eb9f04e7500b467dd7b7394f8ab1364f5b6c3fea112ec818a327e8d03eee6012dadd94911e1275f3c5c43966cbb

test:
  secret_key_base: 4de761949bfe7742d474cc1b071940cdc0b06e5e8bc972ea92a3cb0bd89b51a84fa75a6c5feea3312bcfae96225503705dce19a5d801a69878f9e9d24440685b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
